@startuml class

skin rose

title Classes - Class Diagram

interface Beverage {
    +void prepare()
}

class DarkRoast implements Beverage {
    +void prepare()
}

class Decaf implements Beverage {
    +void prepare()
}

class Espresso implements Beverage {
    +void prepare()
}

class HouseBlend implements Beverage {
    +void prepare()
}

class BaseBevarageDecorator implements Beverage {
    -Beverage wrapee
    +BaseBevarageDecorator(Beverage wrapee)
    +void prepare()
}

BaseBevarageDecorator --o Beverage

class MilkDecorator extends BaseBevarageDecorator {
    ...
}

class SoyDecorator extends BaseBevarageDecorator {
    ...
}

class MochaDecorator extends BaseBevarageDecorator {
    ...
}

class WhipDecorator extends BaseBevarageDecorator {
    ...
}

@enduml