@startuml class

skin rose

title Classes - Class Diagram

interface Beverage {
    +void prepare()
}

class DarkRoast implements Beverage {
    +void prepare()
}

class Decaf implements Beverage {
    +void prepare()
}

class Espresso implements Beverage {
    +void prepare()
}

class HouseBlend implements Beverage {
    +void prepare()
}

class BaseBevarageDecorator implements Beverage {
    -Beverage wrapee
    +BaseBevarageDecorator(Beverage wrapee)
    +void prepare()
}

BaseBevarageDecorator --o Beverage

class MilkDecorator extends BaseBevarageDecorator {
    +MilkDecorator(Beverage wrapee)
    +void prepare()
}

class SoyDecorator extends BaseBevarageDecorator {
    +SoyDecorator(Beverage wrapee)
    +void prepare()
}

class MochaDecorator extends BaseBevarageDecorator {
    +MochaDecorator(Beverage wrapee)
    +void prepare()
}

class WhipDecorator extends BaseBevarageDecorator {
    +WhipDecorator(Beverage wrapee)
    +void prepare()
}

@enduml